version: '3.1'
services:
    base:
        build:
            context: .
        image: ${IMAGE_NAME}
        env_file:
            - ./.env
        container_name: ${CONTAINER_NAME}
        ports:
            - 5000:80
        volumes:
            - ./src:/app
